package org.chai.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.chai.model.AdhockSale;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ADHOCK_SALE.
*/
public class AdhockSaleDao extends AbstractDao<AdhockSale, Long> {

    public static final String TABLENAME = "ADHOCK_SALE";

    /**
     * Properties of entity AdhockSale.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClientRefId = new Property(1, String.class, "clientRefId", false, "CLIENT_REF_ID");
        public final static Property DateOfSale = new Property(2, java.util.Date.class, "dateOfSale", false, "DATE_OF_SALE");
        public final static Property DoYouStockOrsZinc = new Property(3, Boolean.class, "doYouStockOrsZinc", false, "DO_YOU_STOCK_ORS_ZINC");
        public final static Property HowManyZincInStock = new Property(4, Integer.class, "howManyZincInStock", false, "HOW_MANY_ZINC_IN_STOCK");
        public final static Property HowManyOrsInStock = new Property(5, Integer.class, "howManyOrsInStock", false, "HOW_MANY_ORS_IN_STOCK");
        public final static Property IfNoWhy = new Property(6, String.class, "ifNoWhy", false, "IF_NO_WHY");
        public final static Property PointOfsaleMaterial = new Property(7, String.class, "pointOfsaleMaterial", false, "POINT_OFSALE_MATERIAL");
        public final static Property RecommendationNextStep = new Property(8, String.class, "recommendationNextStep", false, "RECOMMENDATION_NEXT_STEP");
        public final static Property RecommendationLevel = new Property(9, String.class, "recommendationLevel", false, "RECOMMENDATION_LEVEL");
        public final static Property GovernmentApproval = new Property(10, String.class, "governmentApproval", false, "GOVERNMENT_APPROVAL");
        public final static Property CustomerId = new Property(11, String.class, "customerId", false, "CUSTOMER_ID");
        public final static Property CustomerRefId = new Property(12, long.class, "customerRefId", false, "CUSTOMER_REF_ID");
    };

    private DaoSession daoSession;

    private Query<AdhockSale> customer_AdhockSalesQuery;

    public AdhockSaleDao(DaoConfig config) {
        super(config);
    }
    
    public AdhockSaleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ADHOCK_SALE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CLIENT_REF_ID' TEXT NOT NULL UNIQUE ," + // 1: clientRefId
                "'DATE_OF_SALE' INTEGER NOT NULL ," + // 2: dateOfSale
                "'DO_YOU_STOCK_ORS_ZINC' INTEGER," + // 3: doYouStockOrsZinc
                "'HOW_MANY_ZINC_IN_STOCK' INTEGER," + // 4: howManyZincInStock
                "'HOW_MANY_ORS_IN_STOCK' INTEGER," + // 5: howManyOrsInStock
                "'IF_NO_WHY' TEXT," + // 6: ifNoWhy
                "'POINT_OFSALE_MATERIAL' TEXT," + // 7: pointOfsaleMaterial
                "'RECOMMENDATION_NEXT_STEP' TEXT," + // 8: recommendationNextStep
                "'RECOMMENDATION_LEVEL' TEXT," + // 9: recommendationLevel
                "'GOVERNMENT_APPROVAL' TEXT," + // 10: governmentApproval
                "'CUSTOMER_ID' TEXT," + // 11: customerId
                "'CUSTOMER_REF_ID' INTEGER NOT NULL );"); // 12: customerRefId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ADHOCK_SALE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AdhockSale entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getClientRefId());
        stmt.bindLong(3, entity.getDateOfSale().getTime());
 
        Boolean doYouStockOrsZinc = entity.getDoYouStockOrsZinc();
        if (doYouStockOrsZinc != null) {
            stmt.bindLong(4, doYouStockOrsZinc ? 1l: 0l);
        }
 
        Integer howManyZincInStock = entity.getHowManyZincInStock();
        if (howManyZincInStock != null) {
            stmt.bindLong(5, howManyZincInStock);
        }
 
        Integer howManyOrsInStock = entity.getHowManyOrsInStock();
        if (howManyOrsInStock != null) {
            stmt.bindLong(6, howManyOrsInStock);
        }
 
        String ifNoWhy = entity.getIfNoWhy();
        if (ifNoWhy != null) {
            stmt.bindString(7, ifNoWhy);
        }
 
        String pointOfsaleMaterial = entity.getPointOfsaleMaterial();
        if (pointOfsaleMaterial != null) {
            stmt.bindString(8, pointOfsaleMaterial);
        }
 
        String recommendationNextStep = entity.getRecommendationNextStep();
        if (recommendationNextStep != null) {
            stmt.bindString(9, recommendationNextStep);
        }
 
        String recommendationLevel = entity.getRecommendationLevel();
        if (recommendationLevel != null) {
            stmt.bindString(10, recommendationLevel);
        }
 
        String governmentApproval = entity.getGovernmentApproval();
        if (governmentApproval != null) {
            stmt.bindString(11, governmentApproval);
        }
 
        String customerId = entity.getCustomerId();
        if (customerId != null) {
            stmt.bindString(12, customerId);
        }
        stmt.bindLong(13, entity.getCustomerRefId());
    }

    @Override
    protected void attachEntity(AdhockSale entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AdhockSale readEntity(Cursor cursor, int offset) {
        AdhockSale entity = new AdhockSale( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // clientRefId
            new java.util.Date(cursor.getLong(offset + 2)), // dateOfSale
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // doYouStockOrsZinc
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // howManyZincInStock
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // howManyOrsInStock
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ifNoWhy
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // pointOfsaleMaterial
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // recommendationNextStep
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // recommendationLevel
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // governmentApproval
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // customerId
            cursor.getLong(offset + 12) // customerRefId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AdhockSale entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClientRefId(cursor.getString(offset + 1));
        entity.setDateOfSale(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setDoYouStockOrsZinc(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setHowManyZincInStock(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setHowManyOrsInStock(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setIfNoWhy(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPointOfsaleMaterial(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setRecommendationNextStep(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRecommendationLevel(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setGovernmentApproval(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCustomerId(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCustomerRefId(cursor.getLong(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AdhockSale entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AdhockSale entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "adhockSales" to-many relationship of Customer. */
    public List<AdhockSale> _queryCustomer_AdhockSales(long customerRefId) {
        synchronized (this) {
            if (customer_AdhockSalesQuery == null) {
                QueryBuilder<AdhockSale> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CustomerRefId.eq(null));
                queryBuilder.orderRaw("DATE_OF_SALE ASC");
                customer_AdhockSalesQuery = queryBuilder.build();
            }
        }
        Query<AdhockSale> query = customer_AdhockSalesQuery.forCurrentThread();
        query.setParameter(0, customerRefId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCustomerDao().getAllColumns());
            builder.append(" FROM ADHOCK_SALE T");
            builder.append(" LEFT JOIN CUSTOMER T0 ON T.'CUSTOMER_REF_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AdhockSale loadCurrentDeep(Cursor cursor, boolean lock) {
        AdhockSale entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Customer customer = loadCurrentOther(daoSession.getCustomerDao(), cursor, offset);
         if(customer != null) {
            entity.setCustomer(customer);
        }

        return entity;    
    }

    public AdhockSale loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AdhockSale> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AdhockSale> list = new ArrayList<AdhockSale>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AdhockSale> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AdhockSale> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
