package org.chai.model;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.chai.model.customerContact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CUSTOMER_CONTACT.
*/
public class customerContactDao extends AbstractDao<customerContact, Long> {

    public static final String TABLENAME = "CUSTOMER_CONTACT";

    /**
     * Properties of entity customerContact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sysid = new Property(1, String.class, "sysid", false, "SYSID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Contact = new Property(3, String.class, "contact", false, "CONTACT");
        public final static Property TypeOfContact = new Property(4, String.class, "typeOfContact", false, "TYPE_OF_CONTACT");
        public final static Property Gender = new Property(5, String.class, "gender", false, "GENDER");
        public final static Property Role = new Property(6, String.class, "role", false, "ROLE");
        public final static Property Qualification = new Property(7, String.class, "qualification", false, "QUALIFICATION");
        public final static Property NetworkOrAssociation = new Property(8, String.class, "networkOrAssociation", false, "NETWORK_OR_ASSOCIATION");
        public final static Property GraduationYear = new Property(9, Integer.class, "graduationYear", false, "GRADUATION_YEAR");
        public final static Property CustomerId = new Property(10, long.class, "customerId", false, "CUSTOMER_ID");
    };

    private DaoSession daoSession;

    private Query<customerContact> customer_ContactsQuery;

    public customerContactDao(DaoConfig config) {
        super(config);
    }
    
    public customerContactDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CUSTOMER_CONTACT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SYSID' TEXT NOT NULL UNIQUE ," + // 1: sysid
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'CONTACT' TEXT NOT NULL ," + // 3: contact
                "'TYPE_OF_CONTACT' TEXT NOT NULL ," + // 4: typeOfContact
                "'GENDER' TEXT NOT NULL ," + // 5: gender
                "'ROLE' TEXT NOT NULL ," + // 6: role
                "'QUALIFICATION' TEXT NOT NULL ," + // 7: qualification
                "'NETWORK_OR_ASSOCIATION' TEXT," + // 8: networkOrAssociation
                "'GRADUATION_YEAR' INTEGER," + // 9: graduationYear
                "'CUSTOMER_ID' INTEGER NOT NULL );"); // 10: customerId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CUSTOMER_CONTACT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, customerContact entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSysid());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getContact());
        stmt.bindString(5, entity.getTypeOfContact());
        stmt.bindString(6, entity.getGender());
        stmt.bindString(7, entity.getRole());
        stmt.bindString(8, entity.getQualification());
 
        String networkOrAssociation = entity.getNetworkOrAssociation();
        if (networkOrAssociation != null) {
            stmt.bindString(9, networkOrAssociation);
        }
 
        Integer graduationYear = entity.getGraduationYear();
        if (graduationYear != null) {
            stmt.bindLong(10, graduationYear);
        }
        stmt.bindLong(11, entity.getCustomerId());
    }

    @Override
    protected void attachEntity(customerContact entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public customerContact readEntity(Cursor cursor, int offset) {
        customerContact entity = new customerContact( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // sysid
            cursor.getString(offset + 2), // name
            cursor.getString(offset + 3), // contact
            cursor.getString(offset + 4), // typeOfContact
            cursor.getString(offset + 5), // gender
            cursor.getString(offset + 6), // role
            cursor.getString(offset + 7), // qualification
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // networkOrAssociation
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // graduationYear
            cursor.getLong(offset + 10) // customerId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, customerContact entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSysid(cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setContact(cursor.getString(offset + 3));
        entity.setTypeOfContact(cursor.getString(offset + 4));
        entity.setGender(cursor.getString(offset + 5));
        entity.setRole(cursor.getString(offset + 6));
        entity.setQualification(cursor.getString(offset + 7));
        entity.setNetworkOrAssociation(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setGraduationYear(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setCustomerId(cursor.getLong(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(customerContact entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(customerContact entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "contacts" to-many relationship of customer. */
    public List<customerContact> _queryCustomer_Contacts(long customerId) {
        synchronized (this) {
            if (customer_ContactsQuery == null) {
                QueryBuilder<customerContact> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CustomerId.eq(null));
                customer_ContactsQuery = queryBuilder.build();
            }
        }
        Query<customerContact> query = customer_ContactsQuery.forCurrentThread();
        query.setParameter(0, customerId);
        return query.list();
    }

}
