package org.chai.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.chai.model.Customer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CUSTOMER.
*/
public class CustomerDao extends AbstractDao<Customer, Long> {

    public static final String TABLENAME = "CUSTOMER";

    /**
     * Properties of entity Customer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uuid = new Property(1, String.class, "uuid", false, "UUID");
        public final static Property Latitude = new Property(2, Double.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(3, Double.class, "longitude", false, "LONGITUDE");
        public final static Property OutletName = new Property(4, String.class, "outletName", false, "OUTLET_NAME");
        public final static Property OutletType = new Property(5, String.class, "outletType", false, "OUTLET_TYPE");
        public final static Property OutletSize = new Property(6, String.class, "outletSize", false, "OUTLET_SIZE");
        public final static Property OutletPicture = new Property(7, byte[].class, "outletPicture", false, "OUTLET_PICTURE");
        public final static Property Split = new Property(8, String.class, "split", false, "SPLIT");
        public final static Property OpeningHours = new Property(9, String.class, "openingHours", false, "OPENING_HOURS");
        public final static Property MajoritySourceOfSupply = new Property(10, String.class, "majoritySourceOfSupply", false, "MAJORITY_SOURCE_OF_SUPPLY");
        public final static Property KeyWholeSalerName = new Property(11, String.class, "keyWholeSalerName", false, "KEY_WHOLE_SALER_NAME");
        public final static Property KeyWholeSalerContact = new Property(12, String.class, "keyWholeSalerContact", false, "KEY_WHOLE_SALER_CONTACT");
        public final static Property BuildingStructure = new Property(13, String.class, "buildingStructure", false, "BUILDING_STRUCTURE");
        public final static Property Equipment = new Property(14, String.class, "equipment", false, "EQUIPMENT");
        public final static Property TypeOfLicence = new Property(15, String.class, "typeOfLicence", false, "TYPE_OF_LICENCE");
        public final static Property DescriptionOfOutletLocation = new Property(16, String.class, "descriptionOfOutletLocation", false, "DESCRIPTION_OF_OUTLET_LOCATION");
        public final static Property NumberOfEmployees = new Property(17, Integer.class, "numberOfEmployees", false, "NUMBER_OF_EMPLOYEES");
        public final static Property NumberOfBranches = new Property(18, Integer.class, "numberOfBranches", false, "NUMBER_OF_BRANCHES");
        public final static Property NumberOfCustomersPerDay = new Property(19, Integer.class, "numberOfCustomersPerDay", false, "NUMBER_OF_CUSTOMERS_PER_DAY");
        public final static Property NumberOfProducts = new Property(20, String.class, "numberOfProducts", false, "NUMBER_OF_PRODUCTS");
        public final static Property RestockFrequency = new Property(21, Integer.class, "restockFrequency", false, "RESTOCK_FREQUENCY");
        public final static Property TurnOver = new Property(22, String.class, "turnOver", false, "TURN_OVER");
        public final static Property TenureLengthYears = new Property(23, Integer.class, "tenureLengthYears", false, "TENURE_LENGTH_YEARS");
        public final static Property TenureLengthMonths = new Property(24, Integer.class, "tenureLengthMonths", false, "TENURE_LENGTH_MONTHS");
        public final static Property DateCreated = new Property(25, java.util.Date.class, "dateCreated", false, "DATE_CREATED");
        public final static Property LastUpdated = new Property(26, java.util.Date.class, "lastUpdated", false, "LAST_UPDATED");
        public final static Property VillageId = new Property(27, long.class, "villageId", false, "VILLAGE_ID");
    };

    private DaoSession daoSession;

    private Query<Customer> village_CustomersQuery;

    public CustomerDao(DaoConfig config) {
        super(config);
    }
    
    public CustomerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CUSTOMER' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'UUID' TEXT NOT NULL UNIQUE ," + // 1: uuid
                "'LATITUDE' REAL," + // 2: latitude
                "'LONGITUDE' REAL," + // 3: longitude
                "'OUTLET_NAME' TEXT NOT NULL ," + // 4: outletName
                "'OUTLET_TYPE' TEXT," + // 5: outletType
                "'OUTLET_SIZE' TEXT," + // 6: outletSize
                "'OUTLET_PICTURE' BLOB," + // 7: outletPicture
                "'SPLIT' TEXT," + // 8: split
                "'OPENING_HOURS' TEXT," + // 9: openingHours
                "'MAJORITY_SOURCE_OF_SUPPLY' TEXT," + // 10: majoritySourceOfSupply
                "'KEY_WHOLE_SALER_NAME' TEXT," + // 11: keyWholeSalerName
                "'KEY_WHOLE_SALER_CONTACT' TEXT," + // 12: keyWholeSalerContact
                "'BUILDING_STRUCTURE' TEXT," + // 13: buildingStructure
                "'EQUIPMENT' TEXT," + // 14: equipment
                "'TYPE_OF_LICENCE' TEXT," + // 15: typeOfLicence
                "'DESCRIPTION_OF_OUTLET_LOCATION' TEXT," + // 16: descriptionOfOutletLocation
                "'NUMBER_OF_EMPLOYEES' INTEGER," + // 17: numberOfEmployees
                "'NUMBER_OF_BRANCHES' INTEGER," + // 18: numberOfBranches
                "'NUMBER_OF_CUSTOMERS_PER_DAY' INTEGER," + // 19: numberOfCustomersPerDay
                "'NUMBER_OF_PRODUCTS' TEXT," + // 20: numberOfProducts
                "'RESTOCK_FREQUENCY' INTEGER," + // 21: restockFrequency
                "'TURN_OVER' TEXT," + // 22: turnOver
                "'TENURE_LENGTH_YEARS' INTEGER," + // 23: tenureLengthYears
                "'TENURE_LENGTH_MONTHS' INTEGER," + // 24: tenureLengthMonths
                "'DATE_CREATED' INTEGER," + // 25: dateCreated
                "'LAST_UPDATED' INTEGER," + // 26: lastUpdated
                "'VILLAGE_ID' INTEGER NOT NULL );"); // 27: villageId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CUSTOMER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Customer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUuid());
 
        Double latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindDouble(3, latitude);
        }
 
        Double longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindDouble(4, longitude);
        }
        stmt.bindString(5, entity.getOutletName());
 
        String outletType = entity.getOutletType();
        if (outletType != null) {
            stmt.bindString(6, outletType);
        }
 
        String outletSize = entity.getOutletSize();
        if (outletSize != null) {
            stmt.bindString(7, outletSize);
        }
 
        byte[] outletPicture = entity.getOutletPicture();
        if (outletPicture != null) {
            stmt.bindBlob(8, outletPicture);
        }
 
        String split = entity.getSplit();
        if (split != null) {
            stmt.bindString(9, split);
        }
 
        String openingHours = entity.getOpeningHours();
        if (openingHours != null) {
            stmt.bindString(10, openingHours);
        }
 
        String majoritySourceOfSupply = entity.getMajoritySourceOfSupply();
        if (majoritySourceOfSupply != null) {
            stmt.bindString(11, majoritySourceOfSupply);
        }
 
        String keyWholeSalerName = entity.getKeyWholeSalerName();
        if (keyWholeSalerName != null) {
            stmt.bindString(12, keyWholeSalerName);
        }
 
        String keyWholeSalerContact = entity.getKeyWholeSalerContact();
        if (keyWholeSalerContact != null) {
            stmt.bindString(13, keyWholeSalerContact);
        }
 
        String buildingStructure = entity.getBuildingStructure();
        if (buildingStructure != null) {
            stmt.bindString(14, buildingStructure);
        }
 
        String equipment = entity.getEquipment();
        if (equipment != null) {
            stmt.bindString(15, equipment);
        }
 
        String typeOfLicence = entity.getTypeOfLicence();
        if (typeOfLicence != null) {
            stmt.bindString(16, typeOfLicence);
        }
 
        String descriptionOfOutletLocation = entity.getDescriptionOfOutletLocation();
        if (descriptionOfOutletLocation != null) {
            stmt.bindString(17, descriptionOfOutletLocation);
        }
 
        Integer numberOfEmployees = entity.getNumberOfEmployees();
        if (numberOfEmployees != null) {
            stmt.bindLong(18, numberOfEmployees);
        }
 
        Integer numberOfBranches = entity.getNumberOfBranches();
        if (numberOfBranches != null) {
            stmt.bindLong(19, numberOfBranches);
        }
 
        Integer numberOfCustomersPerDay = entity.getNumberOfCustomersPerDay();
        if (numberOfCustomersPerDay != null) {
            stmt.bindLong(20, numberOfCustomersPerDay);
        }
 
        String numberOfProducts = entity.getNumberOfProducts();
        if (numberOfProducts != null) {
            stmt.bindString(21, numberOfProducts);
        }
 
        Integer restockFrequency = entity.getRestockFrequency();
        if (restockFrequency != null) {
            stmt.bindLong(22, restockFrequency);
        }
 
        String turnOver = entity.getTurnOver();
        if (turnOver != null) {
            stmt.bindString(23, turnOver);
        }
 
        Integer tenureLengthYears = entity.getTenureLengthYears();
        if (tenureLengthYears != null) {
            stmt.bindLong(24, tenureLengthYears);
        }
 
        Integer tenureLengthMonths = entity.getTenureLengthMonths();
        if (tenureLengthMonths != null) {
            stmt.bindLong(25, tenureLengthMonths);
        }
 
        java.util.Date dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindLong(26, dateCreated.getTime());
        }
 
        java.util.Date lastUpdated = entity.getLastUpdated();
        if (lastUpdated != null) {
            stmt.bindLong(27, lastUpdated.getTime());
        }
        stmt.bindLong(28, entity.getVillageId());
    }

    @Override
    protected void attachEntity(Customer entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Customer readEntity(Cursor cursor, int offset) {
        Customer entity = new Customer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // uuid
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // latitude
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // longitude
            cursor.getString(offset + 4), // outletName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // outletType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // outletSize
            cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7), // outletPicture
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // split
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // openingHours
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // majoritySourceOfSupply
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // keyWholeSalerName
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // keyWholeSalerContact
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // buildingStructure
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // equipment
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // typeOfLicence
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // descriptionOfOutletLocation
            cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17), // numberOfEmployees
            cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18), // numberOfBranches
            cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19), // numberOfCustomersPerDay
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // numberOfProducts
            cursor.isNull(offset + 21) ? null : cursor.getInt(offset + 21), // restockFrequency
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // turnOver
            cursor.isNull(offset + 23) ? null : cursor.getInt(offset + 23), // tenureLengthYears
            cursor.isNull(offset + 24) ? null : cursor.getInt(offset + 24), // tenureLengthMonths
            cursor.isNull(offset + 25) ? null : new java.util.Date(cursor.getLong(offset + 25)), // dateCreated
            cursor.isNull(offset + 26) ? null : new java.util.Date(cursor.getLong(offset + 26)), // lastUpdated
            cursor.getLong(offset + 27) // villageId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Customer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUuid(cursor.getString(offset + 1));
        entity.setLatitude(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setLongitude(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setOutletName(cursor.getString(offset + 4));
        entity.setOutletType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOutletSize(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOutletPicture(cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7));
        entity.setSplit(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setOpeningHours(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMajoritySourceOfSupply(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setKeyWholeSalerName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setKeyWholeSalerContact(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBuildingStructure(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setEquipment(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setTypeOfLicence(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setDescriptionOfOutletLocation(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setNumberOfEmployees(cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17));
        entity.setNumberOfBranches(cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18));
        entity.setNumberOfCustomersPerDay(cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19));
        entity.setNumberOfProducts(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setRestockFrequency(cursor.isNull(offset + 21) ? null : cursor.getInt(offset + 21));
        entity.setTurnOver(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTenureLengthYears(cursor.isNull(offset + 23) ? null : cursor.getInt(offset + 23));
        entity.setTenureLengthMonths(cursor.isNull(offset + 24) ? null : cursor.getInt(offset + 24));
        entity.setDateCreated(cursor.isNull(offset + 25) ? null : new java.util.Date(cursor.getLong(offset + 25)));
        entity.setLastUpdated(cursor.isNull(offset + 26) ? null : new java.util.Date(cursor.getLong(offset + 26)));
        entity.setVillageId(cursor.getLong(offset + 27));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Customer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Customer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "customers" to-many relationship of Village. */
    public List<Customer> _queryVillage_Customers(long villageId) {
        synchronized (this) {
            if (village_CustomersQuery == null) {
                QueryBuilder<Customer> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.VillageId.eq(null));
                village_CustomersQuery = queryBuilder.build();
            }
        }
        Query<Customer> query = village_CustomersQuery.forCurrentThread();
        query.setParameter(0, villageId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getVillageDao().getAllColumns());
            builder.append(" FROM CUSTOMER T");
            builder.append(" LEFT JOIN VILLAGE T0 ON T.'VILLAGE_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Customer loadCurrentDeep(Cursor cursor, boolean lock) {
        Customer entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Village village = loadCurrentOther(daoSession.getVillageDao(), cursor, offset);
         if(village != null) {
            entity.setVillage(village);
        }

        return entity;    
    }

    public Customer loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Customer> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Customer> list = new ArrayList<Customer>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Customer> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Customer> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
