package org.chai.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.chai.model.CustomerContact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CUSTOMER_CONTACT.
*/
public class CustomerContactDao extends AbstractDao<CustomerContact, String> {

    public static final String TABLENAME = "CUSTOMER_CONTACT";

    /**
     * Properties of entity CustomerContact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Uuid = new Property(0, String.class, "uuid", true, "UUID");
        public final static Property Contact = new Property(1, String.class, "contact", false, "CONTACT");
        public final static Property Names = new Property(2, String.class, "names", false, "NAMES");
        public final static Property Gender = new Property(3, String.class, "gender", false, "GENDER");
        public final static Property Role = new Property(4, String.class, "role", false, "ROLE");
        public final static Property CustomerId = new Property(5, String.class, "customerId", false, "CUSTOMER_ID");
        public final static Property IsDirty = new Property(6, Boolean.class, "isDirty", false, "IS_DIRTY");
        public final static Property SyncronisationStatus = new Property(7, Integer.class, "syncronisationStatus", false, "SYNCRONISATION_STATUS");
        public final static Property SyncronisationMessage = new Property(8, String.class, "syncronisationMessage", false, "SYNCRONISATION_MESSAGE");
        public final static Property DateCreated = new Property(9, java.util.Date.class, "dateCreated", false, "DATE_CREATED");
        public final static Property LastUpdated = new Property(10, java.util.Date.class, "lastUpdated", false, "LAST_UPDATED");
    };

    private DaoSession daoSession;

    private Query<CustomerContact> customer_CustomerContactsQuery;

    public CustomerContactDao(DaoConfig config) {
        super(config);
    }
    
    public CustomerContactDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CUSTOMER_CONTACT' (" + //
                "'UUID' TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: uuid
                "'CONTACT' TEXT," + // 1: contact
                "'NAMES' TEXT," + // 2: names
                "'GENDER' TEXT," + // 3: gender
                "'ROLE' TEXT," + // 4: role
                "'CUSTOMER_ID' TEXT NOT NULL ," + // 5: customerId
                "'IS_DIRTY' INTEGER," + // 6: isDirty
                "'SYNCRONISATION_STATUS' INTEGER," + // 7: syncronisationStatus
                "'SYNCRONISATION_MESSAGE' TEXT," + // 8: syncronisationMessage
                "'DATE_CREATED' INTEGER," + // 9: dateCreated
                "'LAST_UPDATED' INTEGER);"); // 10: lastUpdated
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CUSTOMER_CONTACT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CustomerContact entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUuid());
 
        String contact = entity.getContact();
        if (contact != null) {
            stmt.bindString(2, contact);
        }
 
        String names = entity.getNames();
        if (names != null) {
            stmt.bindString(3, names);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(4, gender);
        }
 
        String role = entity.getRole();
        if (role != null) {
            stmt.bindString(5, role);
        }
        stmt.bindString(6, entity.getCustomerId());
 
        Boolean isDirty = entity.getIsDirty();
        if (isDirty != null) {
            stmt.bindLong(7, isDirty ? 1l: 0l);
        }
 
        Integer syncronisationStatus = entity.getSyncronisationStatus();
        if (syncronisationStatus != null) {
            stmt.bindLong(8, syncronisationStatus);
        }
 
        String syncronisationMessage = entity.getSyncronisationMessage();
        if (syncronisationMessage != null) {
            stmt.bindString(9, syncronisationMessage);
        }
 
        java.util.Date dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindLong(10, dateCreated.getTime());
        }
 
        java.util.Date lastUpdated = entity.getLastUpdated();
        if (lastUpdated != null) {
            stmt.bindLong(11, lastUpdated.getTime());
        }
    }

    @Override
    protected void attachEntity(CustomerContact entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CustomerContact readEntity(Cursor cursor, int offset) {
        CustomerContact entity = new CustomerContact( //
            cursor.getString(offset + 0), // uuid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // contact
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // names
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gender
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // role
            cursor.getString(offset + 5), // customerId
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // isDirty
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // syncronisationStatus
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // syncronisationMessage
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)), // dateCreated
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)) // lastUpdated
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CustomerContact entity, int offset) {
        entity.setUuid(cursor.getString(offset + 0));
        entity.setContact(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNames(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGender(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRole(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCustomerId(cursor.getString(offset + 5));
        entity.setIsDirty(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setSyncronisationStatus(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setSyncronisationMessage(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDateCreated(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
        entity.setLastUpdated(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(CustomerContact entity, long rowId) {
        return entity.getUuid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(CustomerContact entity) {
        if(entity != null) {
            return entity.getUuid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "customerContacts" to-many relationship of Customer. */
    public List<CustomerContact> _queryCustomer_CustomerContacts(String customerId) {
        synchronized (this) {
            if (customer_CustomerContactsQuery == null) {
                QueryBuilder<CustomerContact> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CustomerId.eq(null));
                customer_CustomerContactsQuery = queryBuilder.build();
            }
        }
        Query<CustomerContact> query = customer_CustomerContactsQuery.forCurrentThread();
        query.setParameter(0, customerId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCustomerDao().getAllColumns());
            builder.append(" FROM CUSTOMER_CONTACT T");
            builder.append(" LEFT JOIN CUSTOMER T0 ON T.'CUSTOMER_ID'=T0.'UUID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CustomerContact loadCurrentDeep(Cursor cursor, boolean lock) {
        CustomerContact entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Customer customer = loadCurrentOther(daoSession.getCustomerDao(), cursor, offset);
         if(customer != null) {
            entity.setCustomer(customer);
        }

        return entity;    
    }

    public CustomerContact loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CustomerContact> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CustomerContact> list = new ArrayList<CustomerContact>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CustomerContact> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CustomerContact> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
