package org.chai.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.chai.model.region;
import org.chai.model.district;
import org.chai.model.subcounty;
import org.chai.model.parish;
import org.chai.model.village;
import org.chai.model.customer;
import org.chai.model.customerContact;
import org.chai.model.product;
import org.chai.model.order;
import org.chai.model.task;
import org.chai.model.promotion;
import org.chai.model.promotionalItem;
import org.chai.model.sale;

import org.chai.model.regionDao;
import org.chai.model.districtDao;
import org.chai.model.subcountyDao;
import org.chai.model.parishDao;
import org.chai.model.villageDao;
import org.chai.model.customerDao;
import org.chai.model.customerContactDao;
import org.chai.model.productDao;
import org.chai.model.orderDao;
import org.chai.model.taskDao;
import org.chai.model.promotionDao;
import org.chai.model.promotionalItemDao;
import org.chai.model.saleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig regionDaoConfig;
    private final DaoConfig districtDaoConfig;
    private final DaoConfig subcountyDaoConfig;
    private final DaoConfig parishDaoConfig;
    private final DaoConfig villageDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig customerContactDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig promotionDaoConfig;
    private final DaoConfig promotionalItemDaoConfig;
    private final DaoConfig saleDaoConfig;

    private final regionDao regionDao;
    private final districtDao districtDao;
    private final subcountyDao subcountyDao;
    private final parishDao parishDao;
    private final villageDao villageDao;
    private final customerDao customerDao;
    private final customerContactDao customerContactDao;
    private final productDao productDao;
    private final orderDao orderDao;
    private final taskDao taskDao;
    private final promotionDao promotionDao;
    private final promotionalItemDao promotionalItemDao;
    private final saleDao saleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        regionDaoConfig = daoConfigMap.get(regionDao.class).clone();
        regionDaoConfig.initIdentityScope(type);

        districtDaoConfig = daoConfigMap.get(districtDao.class).clone();
        districtDaoConfig.initIdentityScope(type);

        subcountyDaoConfig = daoConfigMap.get(subcountyDao.class).clone();
        subcountyDaoConfig.initIdentityScope(type);

        parishDaoConfig = daoConfigMap.get(parishDao.class).clone();
        parishDaoConfig.initIdentityScope(type);

        villageDaoConfig = daoConfigMap.get(villageDao.class).clone();
        villageDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(customerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        customerContactDaoConfig = daoConfigMap.get(customerContactDao.class).clone();
        customerContactDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(productDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(orderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(taskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        promotionDaoConfig = daoConfigMap.get(promotionDao.class).clone();
        promotionDaoConfig.initIdentityScope(type);

        promotionalItemDaoConfig = daoConfigMap.get(promotionalItemDao.class).clone();
        promotionalItemDaoConfig.initIdentityScope(type);

        saleDaoConfig = daoConfigMap.get(saleDao.class).clone();
        saleDaoConfig.initIdentityScope(type);

        regionDao = new regionDao(regionDaoConfig, this);
        districtDao = new districtDao(districtDaoConfig, this);
        subcountyDao = new subcountyDao(subcountyDaoConfig, this);
        parishDao = new parishDao(parishDaoConfig, this);
        villageDao = new villageDao(villageDaoConfig, this);
        customerDao = new customerDao(customerDaoConfig, this);
        customerContactDao = new customerContactDao(customerContactDaoConfig, this);
        productDao = new productDao(productDaoConfig, this);
        orderDao = new orderDao(orderDaoConfig, this);
        taskDao = new taskDao(taskDaoConfig, this);
        promotionDao = new promotionDao(promotionDaoConfig, this);
        promotionalItemDao = new promotionalItemDao(promotionalItemDaoConfig, this);
        saleDao = new saleDao(saleDaoConfig, this);

        registerDao(region.class, regionDao);
        registerDao(district.class, districtDao);
        registerDao(subcounty.class, subcountyDao);
        registerDao(parish.class, parishDao);
        registerDao(village.class, villageDao);
        registerDao(customer.class, customerDao);
        registerDao(customerContact.class, customerContactDao);
        registerDao(product.class, productDao);
        registerDao(order.class, orderDao);
        registerDao(task.class, taskDao);
        registerDao(promotion.class, promotionDao);
        registerDao(promotionalItem.class, promotionalItemDao);
        registerDao(sale.class, saleDao);
    }
    
    public void clear() {
        regionDaoConfig.getIdentityScope().clear();
        districtDaoConfig.getIdentityScope().clear();
        subcountyDaoConfig.getIdentityScope().clear();
        parishDaoConfig.getIdentityScope().clear();
        villageDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        customerContactDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        taskDaoConfig.getIdentityScope().clear();
        promotionDaoConfig.getIdentityScope().clear();
        promotionalItemDaoConfig.getIdentityScope().clear();
        saleDaoConfig.getIdentityScope().clear();
    }

    public regionDao getRegionDao() {
        return regionDao;
    }

    public districtDao getDistrictDao() {
        return districtDao;
    }

    public subcountyDao getSubcountyDao() {
        return subcountyDao;
    }

    public parishDao getParishDao() {
        return parishDao;
    }

    public villageDao getVillageDao() {
        return villageDao;
    }

    public customerDao getCustomerDao() {
        return customerDao;
    }

    public customerContactDao getCustomerContactDao() {
        return customerContactDao;
    }

    public productDao getProductDao() {
        return productDao;
    }

    public orderDao getOrderDao() {
        return orderDao;
    }

    public taskDao getTaskDao() {
        return taskDao;
    }

    public promotionDao getPromotionDao() {
        return promotionDao;
    }

    public promotionalItemDao getPromotionalItemDao() {
        return promotionalItemDao;
    }

    public saleDao getSaleDao() {
        return saleDao;
    }

}
