package org.chai.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.chai.model.Parish;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PARISH.
*/
public class ParishDao extends AbstractDao<Parish, String> {

    public static final String TABLENAME = "PARISH";

    /**
     * Properties of entity Parish.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Uuid = new Property(0, String.class, "uuid", true, "UUID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property SubCountyId = new Property(2, String.class, "subCountyId", false, "SUB_COUNTY_ID");
    };

    private DaoSession daoSession;

    private Query<Parish> subcounty_ParishesQuery;

    public ParishDao(DaoConfig config) {
        super(config);
    }
    
    public ParishDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PARISH' (" + //
                "'UUID' TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: uuid
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'SUB_COUNTY_ID' TEXT NOT NULL );"); // 2: subCountyId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PARISH'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Parish entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUuid());
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getSubCountyId());
    }

    @Override
    protected void attachEntity(Parish entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Parish readEntity(Cursor cursor, int offset) {
        Parish entity = new Parish( //
            cursor.getString(offset + 0), // uuid
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2) // subCountyId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Parish entity, int offset) {
        entity.setUuid(cursor.getString(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setSubCountyId(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Parish entity, long rowId) {
        return entity.getUuid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Parish entity) {
        if(entity != null) {
            return entity.getUuid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "parishes" to-many relationship of Subcounty. */
    public List<Parish> _querySubcounty_Parishes(String subCountyId) {
        synchronized (this) {
            if (subcounty_ParishesQuery == null) {
                QueryBuilder<Parish> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SubCountyId.eq(null));
                subcounty_ParishesQuery = queryBuilder.build();
            }
        }
        Query<Parish> query = subcounty_ParishesQuery.forCurrentThread();
        query.setParameter(0, subCountyId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSubcountyDao().getAllColumns());
            builder.append(" FROM PARISH T");
            builder.append(" LEFT JOIN SUBCOUNTY T0 ON T.'SUB_COUNTY_ID'=T0.'UUID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Parish loadCurrentDeep(Cursor cursor, boolean lock) {
        Parish entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Subcounty subcounty = loadCurrentOther(daoSession.getSubcountyDao(), cursor, offset);
         if(subcounty != null) {
            entity.setSubcounty(subcounty);
        }

        return entity;    
    }

    public Parish loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Parish> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Parish> list = new ArrayList<Parish>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Parish> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Parish> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
