package org.chai.model;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.chai.model.parish;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PARISH.
*/
public class parishDao extends AbstractDao<parish, Long> {

    public static final String TABLENAME = "PARISH";

    /**
     * Properties of entity parish.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sysid = new Property(1, String.class, "sysid", false, "SYSID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property SubcountyId = new Property(3, long.class, "subcountyId", false, "SUBCOUNTY_ID");
    };

    private DaoSession daoSession;

    private Query<parish> subcounty_ParishesQuery;

    public parishDao(DaoConfig config) {
        super(config);
    }
    
    public parishDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PARISH' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SYSID' TEXT NOT NULL UNIQUE ," + // 1: sysid
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'SUBCOUNTY_ID' INTEGER NOT NULL );"); // 3: subcountyId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PARISH'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, parish entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSysid());
        stmt.bindString(3, entity.getName());
        stmt.bindLong(4, entity.getSubcountyId());
    }

    @Override
    protected void attachEntity(parish entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public parish readEntity(Cursor cursor, int offset) {
        parish entity = new parish( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // sysid
            cursor.getString(offset + 2), // name
            cursor.getLong(offset + 3) // subcountyId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, parish entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSysid(cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setSubcountyId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(parish entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(parish entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "parishes" to-many relationship of subcounty. */
    public List<parish> _querySubcounty_Parishes(long subcountyId) {
        synchronized (this) {
            if (subcounty_ParishesQuery == null) {
                QueryBuilder<parish> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SubcountyId.eq(null));
                subcounty_ParishesQuery = queryBuilder.build();
            }
        }
        Query<parish> query = subcounty_ParishesQuery.forCurrentThread();
        query.setParameter(0, subcountyId);
        return query.list();
    }

}
