package org.chai.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.chai.model.SaleData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SALE_DATA.
*/
public class SaleDataDao extends AbstractDao<SaleData, Long> {

    public static final String TABLENAME = "SALE_DATA";

    /**
     * Properties of entity SaleData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uuid = new Property(1, String.class, "uuid", false, "UUID");
        public final static Property Quantity = new Property(2, int.class, "quantity", false, "QUANTITY");
        public final static Property Price = new Property(3, int.class, "price", false, "PRICE");
        public final static Property SaleId = new Property(4, long.class, "saleId", false, "SALE_ID");
        public final static Property ProductId = new Property(5, long.class, "productId", false, "PRODUCT_ID");
    };

    private DaoSession daoSession;

    private Query<SaleData> sale_SalesDatasQuery;
    private Query<SaleData> product_SalesDatasQuery;

    public SaleDataDao(DaoConfig config) {
        super(config);
    }
    
    public SaleDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SALE_DATA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'UUID' TEXT NOT NULL UNIQUE ," + // 1: uuid
                "'QUANTITY' INTEGER NOT NULL ," + // 2: quantity
                "'PRICE' INTEGER NOT NULL ," + // 3: price
                "'SALE_ID' INTEGER NOT NULL ," + // 4: saleId
                "'PRODUCT_ID' INTEGER NOT NULL );"); // 5: productId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SALE_DATA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SaleData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUuid());
        stmt.bindLong(3, entity.getQuantity());
        stmt.bindLong(4, entity.getPrice());
        stmt.bindLong(5, entity.getSaleId());
        stmt.bindLong(6, entity.getProductId());
    }

    @Override
    protected void attachEntity(SaleData entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SaleData readEntity(Cursor cursor, int offset) {
        SaleData entity = new SaleData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // uuid
            cursor.getInt(offset + 2), // quantity
            cursor.getInt(offset + 3), // price
            cursor.getLong(offset + 4), // saleId
            cursor.getLong(offset + 5) // productId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SaleData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUuid(cursor.getString(offset + 1));
        entity.setQuantity(cursor.getInt(offset + 2));
        entity.setPrice(cursor.getInt(offset + 3));
        entity.setSaleId(cursor.getLong(offset + 4));
        entity.setProductId(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SaleData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SaleData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "salesDatas" to-many relationship of Sale. */
    public List<SaleData> _querySale_SalesDatas(long saleId) {
        synchronized (this) {
            if (sale_SalesDatasQuery == null) {
                QueryBuilder<SaleData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SaleId.eq(null));
                sale_SalesDatasQuery = queryBuilder.build();
            }
        }
        Query<SaleData> query = sale_SalesDatasQuery.forCurrentThread();
        query.setParameter(0, saleId);
        return query.list();
    }

    /** Internal query to resolve the "salesDatas" to-many relationship of Product. */
    public List<SaleData> _queryProduct_SalesDatas(long productId) {
        synchronized (this) {
            if (product_SalesDatasQuery == null) {
                QueryBuilder<SaleData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ProductId.eq(null));
                product_SalesDatasQuery = queryBuilder.build();
            }
        }
        Query<SaleData> query = product_SalesDatasQuery.forCurrentThread();
        query.setParameter(0, productId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSaleDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getProductDao().getAllColumns());
            builder.append(" FROM SALE_DATA T");
            builder.append(" LEFT JOIN SALE T0 ON T.'SALE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PRODUCT T1 ON T.'PRODUCT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SaleData loadCurrentDeep(Cursor cursor, boolean lock) {
        SaleData entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Sale sale = loadCurrentOther(daoSession.getSaleDao(), cursor, offset);
         if(sale != null) {
            entity.setSale(sale);
        }
        offset += daoSession.getSaleDao().getAllColumns().length;

        Product product = loadCurrentOther(daoSession.getProductDao(), cursor, offset);
         if(product != null) {
            entity.setProduct(product);
        }

        return entity;    
    }

    public SaleData loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SaleData> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SaleData> list = new ArrayList<SaleData>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SaleData> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SaleData> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
