package org.chai.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import org.chai.model.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table USER.
*/
public class UserDao extends AbstractDao<User, String> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Uuid = new Property(0, String.class, "uuid", true, "UUID");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property Password = new Property(2, String.class, "password", false, "PASSWORD");
        public final static Property Enabled = new Property(3, boolean.class, "enabled", false, "ENABLED");
        public final static Property Accountexpired = new Property(4, boolean.class, "accountexpired", false, "ACCOUNTEXPIRED");
        public final static Property Accountlocked = new Property(5, boolean.class, "accountlocked", false, "ACCOUNTLOCKED");
        public final static Property Passwordexpired = new Property(6, Boolean.class, "passwordexpired", false, "PASSWORDEXPIRED");
        public final static Property Role = new Property(7, String.class, "role", false, "ROLE");
    };

    private DaoSession daoSession;


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'USER' (" + //
                "'UUID' TEXT PRIMARY KEY NOT NULL ," + // 0: uuid
                "'USER_NAME' TEXT NOT NULL ," + // 1: userName
                "'PASSWORD' TEXT NOT NULL ," + // 2: password
                "'ENABLED' INTEGER NOT NULL ," + // 3: enabled
                "'ACCOUNTEXPIRED' INTEGER NOT NULL ," + // 4: accountexpired
                "'ACCOUNTLOCKED' INTEGER NOT NULL ," + // 5: accountlocked
                "'PASSWORDEXPIRED' INTEGER," + // 6: passwordexpired
                "'ROLE' TEXT);"); // 7: role
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUuid());
        stmt.bindString(2, entity.getUserName());
        stmt.bindString(3, entity.getPassword());
        stmt.bindLong(4, entity.getEnabled() ? 1l: 0l);
        stmt.bindLong(5, entity.getAccountexpired() ? 1l: 0l);
        stmt.bindLong(6, entity.getAccountlocked() ? 1l: 0l);
 
        Boolean passwordexpired = entity.getPasswordexpired();
        if (passwordexpired != null) {
            stmt.bindLong(7, passwordexpired ? 1l: 0l);
        }
 
        String role = entity.getRole();
        if (role != null) {
            stmt.bindString(8, role);
        }
    }

    @Override
    protected void attachEntity(User entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.getString(offset + 0), // uuid
            cursor.getString(offset + 1), // userName
            cursor.getString(offset + 2), // password
            cursor.getShort(offset + 3) != 0, // enabled
            cursor.getShort(offset + 4) != 0, // accountexpired
            cursor.getShort(offset + 5) != 0, // accountlocked
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // passwordexpired
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // role
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setUuid(cursor.getString(offset + 0));
        entity.setUserName(cursor.getString(offset + 1));
        entity.setPassword(cursor.getString(offset + 2));
        entity.setEnabled(cursor.getShort(offset + 3) != 0);
        entity.setAccountexpired(cursor.getShort(offset + 4) != 0);
        entity.setAccountlocked(cursor.getShort(offset + 5) != 0);
        entity.setPasswordexpired(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setRole(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(User entity, long rowId) {
        return entity.getUuid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(User entity) {
        if(entity != null) {
            return entity.getUuid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
