package org.chai.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.chai.model.DetailerStock;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DETAILER_STOCK.
*/
public class DetailerStockDao extends AbstractDao<DetailerStock, String> {

    public static final String TABLENAME = "DETAILER_STOCK";

    /**
     * Properties of entity DetailerStock.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Uuid = new Property(0, String.class, "uuid", true, "UUID");
        public final static Property Brand = new Property(1, String.class, "brand", false, "BRAND");
        public final static Property Category = new Property(2, String.class, "category", false, "CATEGORY");
        public final static Property StockLevel = new Property(3, double.class, "stockLevel", false, "STOCK_LEVEL");
        public final static Property BuyingPrice = new Property(4, Double.class, "buyingPrice", false, "BUYING_PRICE");
        public final static Property SellingPrice = new Property(5, Double.class, "sellingPrice", false, "SELLING_PRICE");
        public final static Property PackSize = new Property(6, String.class, "packSize", false, "PACK_SIZE");
        public final static Property DetailerId = new Property(7, String.class, "detailerId", false, "DETAILER_ID");
        public final static Property MalariadetailId = new Property(8, String.class, "malariadetailId", false, "MALARIADETAIL_ID");
        public final static Property IsDirty = new Property(9, Boolean.class, "isDirty", false, "IS_DIRTY");
        public final static Property SyncronisationStatus = new Property(10, Integer.class, "syncronisationStatus", false, "SYNCRONISATION_STATUS");
        public final static Property SyncronisationMessage = new Property(11, String.class, "syncronisationMessage", false, "SYNCRONISATION_MESSAGE");
        public final static Property DateCreated = new Property(12, java.util.Date.class, "dateCreated", false, "DATE_CREATED");
        public final static Property LastUpdated = new Property(13, java.util.Date.class, "lastUpdated", false, "LAST_UPDATED");
    };

    private DaoSession daoSession;

    private Query<DetailerStock> detailerCall_DetailerStocksQuery;
    private Query<DetailerStock> malariaDetail_DetailerMalariaStocksQuery;

    public DetailerStockDao(DaoConfig config) {
        super(config);
    }
    
    public DetailerStockDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DETAILER_STOCK' (" + //
                "'UUID' TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: uuid
                "'BRAND' TEXT NOT NULL ," + // 1: brand
                "'CATEGORY' TEXT NOT NULL ," + // 2: category
                "'STOCK_LEVEL' REAL NOT NULL ," + // 3: stockLevel
                "'BUYING_PRICE' REAL," + // 4: buyingPrice
                "'SELLING_PRICE' REAL," + // 5: sellingPrice
                "'PACK_SIZE' TEXT," + // 6: packSize
                "'DETAILER_ID' TEXT NOT NULL ," + // 7: detailerId
                "'MALARIADETAIL_ID' TEXT NOT NULL ," + // 8: malariadetailId
                "'IS_DIRTY' INTEGER," + // 9: isDirty
                "'SYNCRONISATION_STATUS' INTEGER," + // 10: syncronisationStatus
                "'SYNCRONISATION_MESSAGE' TEXT," + // 11: syncronisationMessage
                "'DATE_CREATED' INTEGER," + // 12: dateCreated
                "'LAST_UPDATED' INTEGER);"); // 13: lastUpdated
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DETAILER_STOCK'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DetailerStock entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUuid());
        stmt.bindString(2, entity.getBrand());
        stmt.bindString(3, entity.getCategory());
        stmt.bindDouble(4, entity.getStockLevel());
 
        Double buyingPrice = entity.getBuyingPrice();
        if (buyingPrice != null) {
            stmt.bindDouble(5, buyingPrice);
        }
 
        Double sellingPrice = entity.getSellingPrice();
        if (sellingPrice != null) {
            stmt.bindDouble(6, sellingPrice);
        }
 
        String packSize = entity.getPackSize();
        if (packSize != null) {
            stmt.bindString(7, packSize);
        }
        stmt.bindString(8, entity.getDetailerId());
        stmt.bindString(9, entity.getMalariadetailId());
 
        Boolean isDirty = entity.getIsDirty();
        if (isDirty != null) {
            stmt.bindLong(10, isDirty ? 1l: 0l);
        }
 
        Integer syncronisationStatus = entity.getSyncronisationStatus();
        if (syncronisationStatus != null) {
            stmt.bindLong(11, syncronisationStatus);
        }
 
        String syncronisationMessage = entity.getSyncronisationMessage();
        if (syncronisationMessage != null) {
            stmt.bindString(12, syncronisationMessage);
        }
 
        java.util.Date dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindLong(13, dateCreated.getTime());
        }
 
        java.util.Date lastUpdated = entity.getLastUpdated();
        if (lastUpdated != null) {
            stmt.bindLong(14, lastUpdated.getTime());
        }
    }

    @Override
    protected void attachEntity(DetailerStock entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DetailerStock readEntity(Cursor cursor, int offset) {
        DetailerStock entity = new DetailerStock( //
            cursor.getString(offset + 0), // uuid
            cursor.getString(offset + 1), // brand
            cursor.getString(offset + 2), // category
            cursor.getDouble(offset + 3), // stockLevel
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // buyingPrice
            cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5), // sellingPrice
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // packSize
            cursor.getString(offset + 7), // detailerId
            cursor.getString(offset + 8), // malariadetailId
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // isDirty
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // syncronisationStatus
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // syncronisationMessage
            cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)), // dateCreated
            cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)) // lastUpdated
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DetailerStock entity, int offset) {
        entity.setUuid(cursor.getString(offset + 0));
        entity.setBrand(cursor.getString(offset + 1));
        entity.setCategory(cursor.getString(offset + 2));
        entity.setStockLevel(cursor.getDouble(offset + 3));
        entity.setBuyingPrice(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setSellingPrice(cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5));
        entity.setPackSize(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDetailerId(cursor.getString(offset + 7));
        entity.setMalariadetailId(cursor.getString(offset + 8));
        entity.setIsDirty(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setSyncronisationStatus(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setSyncronisationMessage(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDateCreated(cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)));
        entity.setLastUpdated(cursor.isNull(offset + 13) ? null : new java.util.Date(cursor.getLong(offset + 13)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(DetailerStock entity, long rowId) {
        return entity.getUuid();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(DetailerStock entity) {
        if(entity != null) {
            return entity.getUuid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "detailerStocks" to-many relationship of DetailerCall. */
    public List<DetailerStock> _queryDetailerCall_DetailerStocks(String detailerId) {
        synchronized (this) {
            if (detailerCall_DetailerStocksQuery == null) {
                QueryBuilder<DetailerStock> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DetailerId.eq(null));
                detailerCall_DetailerStocksQuery = queryBuilder.build();
            }
        }
        Query<DetailerStock> query = detailerCall_DetailerStocksQuery.forCurrentThread();
        query.setParameter(0, detailerId);
        return query.list();
    }

    /** Internal query to resolve the "detailerMalariaStocks" to-many relationship of MalariaDetail. */
    public List<DetailerStock> _queryMalariaDetail_DetailerMalariaStocks(String malariadetailId) {
        synchronized (this) {
            if (malariaDetail_DetailerMalariaStocksQuery == null) {
                QueryBuilder<DetailerStock> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MalariadetailId.eq(null));
                malariaDetail_DetailerMalariaStocksQuery = queryBuilder.build();
            }
        }
        Query<DetailerStock> query = malariaDetail_DetailerMalariaStocksQuery.forCurrentThread();
        query.setParameter(0, malariadetailId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDetailerCallDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMalariaDetailDao().getAllColumns());
            builder.append(" FROM DETAILER_STOCK T");
            builder.append(" LEFT JOIN DETAILER_CALL T0 ON T.'DETAILER_ID'=T0.'UUID'");
            builder.append(" LEFT JOIN MALARIA_DETAIL T1 ON T.'MALARIADETAIL_ID'=T1.'UUID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DetailerStock loadCurrentDeep(Cursor cursor, boolean lock) {
        DetailerStock entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DetailerCall detailerCall = loadCurrentOther(daoSession.getDetailerCallDao(), cursor, offset);
         if(detailerCall != null) {
            entity.setDetailerCall(detailerCall);
        }
        offset += daoSession.getDetailerCallDao().getAllColumns().length;

        MalariaDetail malariaDetail = loadCurrentOther(daoSession.getMalariaDetailDao(), cursor, offset);
         if(malariaDetail != null) {
            entity.setMalariaDetail(malariaDetail);
        }

        return entity;    
    }

    public DetailerStock loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DetailerStock> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DetailerStock> list = new ArrayList<DetailerStock>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DetailerStock> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DetailerStock> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
